// Mocks generated by Mockito 5.4.6 from annotations
// in trizy_app/test/services/orders_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:trizy_app/utils/networking_manager.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkingManager extends _i1.Mock implements _i2.NetworkingManager {
  MockNetworkingManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  int get maxRetryAttempts => (super.noSuchMethod(
        Invocation.getter(#maxRetryAttempts),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<Map<String, dynamic>> post({
    required String? endpoint,
    required Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, String>? urlParams,
    bool? addAuthToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #headers: headers,
            #urlParams: urlParams,
            #addAuthToken: addAuthToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> get({
    required String? endpoint,
    Map<String, String>? headers,
    Map<String, String>? urlParams,
    Map<String, String>? queryParams,
    bool? addAuthToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #endpoint: endpoint,
            #headers: headers,
            #urlParams: urlParams,
            #queryParams: queryParams,
            #addAuthToken: addAuthToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> delete({
    required String? endpoint,
    Map<String, String>? headers,
    Map<String, String>? urlParams,
    Map<String, String>? queryParams,
    bool? addAuthToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #endpoint: endpoint,
            #headers: headers,
            #urlParams: urlParams,
            #queryParams: queryParams,
            #addAuthToken: addAuthToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> patch({
    required String? endpoint,
    required Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, String>? urlParams,
    bool? addAuthToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #headers: headers,
            #urlParams: urlParams,
            #addAuthToken: addAuthToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> put({
    required String? endpoint,
    required Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, String>? urlParams,
    bool? addAuthToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [],
          {
            #endpoint: endpoint,
            #body: body,
            #headers: headers,
            #urlParams: urlParams,
            #addAuthToken: addAuthToken,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
